name: PNET_env
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.7.1
  # - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attrs=23.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - blas=1.0 
  - bleach=6.0.0
  - bottleneck=1.3.5
  - bzip2=1.0.8 
  - ca-certificates
  - cffi=1.15.1
  - comm=0.1.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - flit-core=3.9.0
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=68.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_resources=6.0.1
  - ipykernel=6.25.1
  - ipython=8.14.0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.1.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter=1.0.0=py_2
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_server=1.23.6
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.8
  - krb5=1.20.1
  - lerc=3.0
  - libcxx=16.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libgfortran
  - libgfortran5=11.3.0
  - libiconv=1.17
  - libllvm12=12.0.1
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.4
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mistune=3.0.1
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.7.4
  - nbconvert-core=7.7.4
  - nbconvert-pandoc=7.7.4
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.5
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy-base=1.25.2
  - openssl=3.0.10
  - packaging=23.1
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.3
  - qtconsole-base=5.4.3
  - qtpy=2.3.1
  - qtwebkit=5.212
  - readline=8.2
  - send2trash=1.8.0
  - setuptools=68.0.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2
  - sqlite=3.41.2
  - stack_data=0.6.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing_extensions=4.7.1
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.6.2
  - wheel=0.38.4
  - widgetsnbextension=4.0.8
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - cachetools==5.3.1
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - flatbuffers==23.5.26
      - fonttools==4.42.1
      - gast==0.4.0
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.57.0
      - h5py==3.9.0
      - joblib==1.3.2
      - keras==2.13.1
      - kiwisolver==1.4.4
      - libclang==16.0.6
      - markdown==3.4.4
      - markupsafe==2.1.3
      - matplotlib
      - networkx==3.1
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pandas==1.5.3
      - pillow==10.0.0
      - protobuf
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyparsing==3.0.9
      - pytz==2023.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorflow-estimator==2.13.0
      - tensorflow-macos==2.13.0
      - tensorflow-metal==1.0.1
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - urllib3==1.26.16
      - werkzeug==2.3.7
      - wrapt==1.15.0
